import { Item, Language, Rarity, Tome, Translations, Weapon } from "./types";

const rarityPalette: Record<Rarity, string> = {
  common: "#9AA5B1",
  uncommon: "#00D140",
  rare: "#39A0FF",
  epic: "#B84CFF",
  legendary: "#FFD867",
};

export const translations: Record<Language, Translations> = {
  es: {
    levelUp: "¡SUBISTE DE NIVEL!",
    chooseUpgrade: "Elige una mejora:",
    weapon: "ARMA",
    tome: "TOMO",
    item: "ÍTEM",
    damage: "Daño",
    fireRate: "Cadencia",
    range: "Alcance",
    level: "Nivel",
    wave: "Wave",
    weapons: "Armas:",
    tomes: "Tomos:",
    items: "Ítems:",
    movement: "WASD - Movimiento",
    restart: "R - Reiniciar",
    pause: "ESC - Pausa",
    sprint: "SPACE - Correr",
    autoShoot: "Disparo automático",
    gameOver: "GAME OVER",
    finalScore: "Puntuación",
    finalLevel: "Nivel alcanzado",
    finalWave: "Wave alcanzado",
    playAgain: "Jugar de nuevo",
    leaderboard: "TOP 10",
    stats: "Estadísticas",
    continue: "Continuar",
    paused: "PAUSA",
    tutorial: {
      move: "Usa WASD para moverte",
    },
  },
  en: {
    levelUp: "LEVEL UP!",
    chooseUpgrade: "Choose an upgrade:",
    weapon: "WEAPON",
    tome: "TOME",
    item: "ITEM",
    damage: "Damage",
    fireRate: "Fire Rate",
    range: "Range",
    level: "Level",
    wave: "Wave",
    weapons: "Weapons:",
    tomes: "Tomes:",
    items: "Items:",
    movement: "WASD - Movement",
    restart: "R - Restart",
    pause: "ESC - Pause",
    sprint: "SPACE - Sprint",
    autoShoot: "Auto Shoot",
    gameOver: "GAME OVER",
    finalScore: "Score",
    finalLevel: "Level Reached",
    finalWave: "Wave Reached",
    playAgain: "Play Again",
    leaderboard: "TOP 10",
    stats: "Stats",
    continue: "Continue",
    paused: "PAUSED",
    tutorial: {
      move: "Use WASD to move",
    },
  },
};

export const WEAPONS: Weapon[] = [
  {
    id: "pistol",
    name: "Pistola",
    damage: 1,
    fireRate: 2,
    range: 250,
    projectileSpeed: 8,
    rarity: "common",
    color: rarityPalette.common,
    level: 1,
  },
  {
    id: "shotgun",
    name: "Escopeta",
    damage: 3,
    fireRate: 0.8,
    range: 180,
    projectileSpeed: 6,
    rarity: "uncommon",
    color: rarityPalette.uncommon,
    special: "spread",
    level: 1,
  },
  {
    id: "smg",
    name: "SMG",
    damage: 0.7,
    fireRate: 6,
    range: 200,
    projectileSpeed: 10,
    rarity: "rare",
    color: rarityPalette.rare,
    level: 1,
  },
  {
    id: "rocket",
    name: "Lanzacohetes",
    damage: 8,
    fireRate: 0.5,
    range: 350,
    projectileSpeed: 5,
    rarity: "epic",
    color: rarityPalette.epic,
    special: "aoe",
    level: 1,
  },
  {
    id: "laser",
    name: "Láser",
    damage: 2,
    fireRate: 4,
    range: 400,
    projectileSpeed: 15,
    rarity: "epic",
    color: rarityPalette.epic,
    special: "pierce",
    level: 1,
  },
  {
    id: "railgun",
    name: "Railgun",
    damage: 12,
    fireRate: 0.3,
    range: 500,
    projectileSpeed: 20,
    rarity: "legendary",
    color: rarityPalette.legendary,
    special: "pierce",
    level: 1,
  },
  {
    id: "minigun",
    name: "Minigun",
    damage: 0.5,
    fireRate: 10,
    range: 220,
    projectileSpeed: 12,
    rarity: "legendary",
    color: rarityPalette.legendary,
    special: "rapid",
    level: 1,
  },
  {
    id: "electric",
    name: "Arma Eléctrica",
    damage: 1.5,
    fireRate: 3,
    range: 300,
    projectileSpeed: 10,
    rarity: "epic",
    color: rarityPalette.epic,
    special: "chain",
    level: 1,
  },
  {
    id: "flamethrower",
    name: "Lanzallamas",
    damage: 0.8,
    fireRate: 8,
    range: 150,
    projectileSpeed: 6,
    rarity: "rare",
    color: rarityPalette.rare,
    special: "fire",
    level: 1,
  },
  {
    id: "frostbow",
    name: "Arco Congelante",
    damage: 1.2,
    fireRate: 2,
    range: 350,
    projectileSpeed: 9,
    rarity: "epic",
    color: rarityPalette.epic,
    special: "freeze",
    level: 1,
  },
  {
    id: "homing",
    name: "Misil Teledirigido",
    damage: 4,
    fireRate: 1,
    range: 400,
    projectileSpeed: 7,
    rarity: "legendary",
    color: rarityPalette.legendary,
    special: "homing",
    level: 1,
  },
];

export const TOMES: Tome[] = [
  {
    id: "power",
    name: "Tomo de Poder",
    description: "+10% Daño",
    effect: "damage",
    value: 1.1,
    rarity: "rare",
    color: rarityPalette.rare,
    level: 1,
  },
  {
    id: "speed",
    name: "Tomo de Velocidad",
    description: "+5% Velocidad",
    effect: "speed",
    value: 1.05,
    rarity: "uncommon",
    color: rarityPalette.uncommon,
    level: 1,
  },
  {
    id: "bounce",
    name: "Tomo de Rebote",
    description: "+1 Rebote (Enemigos)",
    effect: "bounce",
    value: 1,
    rarity: "epic",
    color: rarityPalette.epic,
    level: 1,
  },
  {
    id: "range",
    name: "Tomo de Alcance",
    description: "+10% Alcance",
    effect: "range",
    value: 1.1,
    rarity: "uncommon",
    color: rarityPalette.uncommon,
    level: 1,
  },
  {
    id: "precision",
    name: "Tomo de Precisión",
    description: "+10% Precisión",
    effect: "precision",
    value: 1.1,
    rarity: "rare",
    color: rarityPalette.rare,
    level: 1,
  },
  {
    id: "multi",
    name: "Tomo Múltiple",
    description: "+1 Proyectil",
    effect: "multishot",
    value: 1,
    rarity: "legendary",
    color: rarityPalette.legendary,
    level: 1,
  },
  {
    id: "regen",
    name: "Tomo de Regeneración",
    description: "Regenera 1 HP cada 5s",
    effect: "regen",
    value: 1,
    rarity: "uncommon",
    color: rarityPalette.uncommon,
    level: 1,
  },
  {
    id: "magnet",
    name: "Tomo de Magnetismo",
    description: "+10% Rango de imán",
    effect: "magnet",
    value: 1.1,
    rarity: "common",
    color: rarityPalette.common,
    level: 1,
  },
  {
    id: "fire",
    name: "Tomo de Cadencia",
    description: "+10% Cadencia",
    effect: "fireRate",
    value: 1.1,
    rarity: "rare",
    color: rarityPalette.rare,
    level: 1,
  },
];

export const ITEMS: Item[] = [
  {
    id: "windboots",
    name: "Botas de Viento",
    description: "+5% velocidad",
    effect: "speedboost",
    rarity: "common",
    color: rarityPalette.common,
  },
  {
    id: "fastgloves",
    name: "Guantes Rápidos",
    description: "+5% cadencia",
    effect: "firerateitem",
    rarity: "common",
    color: rarityPalette.common,
  },
  {
    id: "lightvest",
    name: "Chaleco Ligero",
    description: "+10 HP máximo",
    effect: "maxhp10",
    rarity: "common",
    color: rarityPalette.common,
  },
  {
    id: "tacticalbelt",
    name: "Cinturón Táctico",
    description: "+10% magnetismo",
    effect: "magnetitem",
    rarity: "common",
    color: rarityPalette.common,
  },
  {
    id: "oldclock",
    name: "Reloj Antiguo",
    description: "+5% duración powerups",
    effect: "powerupduration",
    rarity: "common",
    color: rarityPalette.common,
  },
  {
    id: "rustyring",
    name: "Anillo Oxidado",
    description: "+10 XP por kill",
    effect: "xpbonus",
    rarity: "common",
    color: rarityPalette.common,
  },
  {
    id: "combatglasses",
    name: "Gafas de Combate",
    description: "+10% precisión",
    effect: "precisionitem",
    rarity: "rare",
    color: rarityPalette.rare,
  },
  {
    id: "reinforcedpants",
    name: "Pantalones Reforzados",
    description: "-5% daño recibido",
    effect: "damagereduction",
    rarity: "rare",
    color: rarityPalette.rare,
  },
  {
    id: "bouncegloves",
    name: "Guantes de Rebote",
    description: "+1 rebote",
    effect: "bounceitem",
    rarity: "rare",
    color: rarityPalette.rare,
  },
  {
    id: "energyclock",
    name: "Reloj de Energía",
    description: "+10% cadencia global",
    effect: "globalfirerate",
    rarity: "rare",
    color: rarityPalette.rare,
  },
  {
    id: "ballistichelmet",
    name: "Casco Balístico",
    description: "Inmunidad 1er golpe/wave",
    effect: "firsthitimmune",
    rarity: "rare",
    color: rarityPalette.rare,
  },
  {
    id: "jetboots",
    name: "Botas Jet",
    description: "+15% velocidad",
    effect: "jetspeed",
    rarity: "epic",
    color: rarityPalette.epic,
  },
  {
    id: "reactiveshield",
    name: "Escudo Reactivo",
    description: "Onda empuja enemigos",
    effect: "reactiveshield",
    rarity: "epic",
    color: rarityPalette.epic,
  },
  {
    id: "chaosamuleto",
    name: "Amuleto del Caos",
    description: "Daño +10% a +50%",
    effect: "chaosdamage",
    rarity: "epic",
    color: rarityPalette.epic,
  },
  {
    id: "ironmedal",
    name: "Medalla de Hierro",
    description: "+15% HP máximo",
    effect: "maxhp15",
    rarity: "epic",
    color: rarityPalette.epic,
  },
  {
    id: "heavyvest",
    name: "Chaleco Pesado",
    description: "-10% velocidad, -25% daño",
    effect: "heavyarmor",
    rarity: "epic",
    color: rarityPalette.epic,
  },
  {
    id: "plasmafragment",
    name: "Fragmento de Plasma",
    description: "+1 rebote +15% alcance",
    effect: "plasmafrag",
    rarity: "epic",
    color: rarityPalette.epic,
  },
  {
    id: "voidcore",
    name: "Núcleo del Vacío",
    description: "XP Doble",
    effect: "doublexp",
    rarity: "legendary",
    color: rarityPalette.legendary,
  },
  {
    id: "solargauntlet",
    name: "Guantelete Solar",
    description: "Proyectil cada 10 kills",
    effect: "solargauntlet",
    rarity: "legendary",
    color: rarityPalette.legendary,
  },
  {
    id: "infernalengine",
    name: "Motor Infernal",
    description: "+25% velocidad +20% daño, +10% daño recibido",
    effect: "infernalengine",
    rarity: "legendary",
    color: rarityPalette.legendary,
  },
  {
    id: "bloodstone",
    name: "Piedra de Sangre",
    description: "5 HP cada 30 kills",
    effect: "bloodstone",
    rarity: "legendary",
    color: rarityPalette.legendary,
  },
  {
    id: "hordetotem",
    name: "Tótem de la Horda",
    description: "+1 enemigo spawn, +2 XP/kill",
    effect: "hordetotem",
    rarity: "legendary",
    color: rarityPalette.legendary,
  },
  {
    id: "artificialheart",
    name: "Corazón Artificial",
    description: "+50 HP permanente",
    effect: "artificialheart",
    rarity: "legendary",
    color: rarityPalette.legendary,
  },
  {
    id: "infinitylens",
    name: "Lente del Infinito",
    description: "+10% todos los stats",
    effect: "infinitylens",
    rarity: "legendary",
    color: rarityPalette.legendary,
  },
];

export const rarityColors: Record<Rarity, string> = rarityPalette;
